# Generated by Django 5.0 on 2024-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_alter_contact_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
