# Generated by Django 5.0 on 2024-01-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0003_alter_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
